# Generated by Django 4.2.5 on 2023-10-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(upload_to='about')),
                ('about_text1', models.CharField(max_length=150)),
                ('about_text2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('text4', models.CharField(max_length=255)),
                ('banner_img', models.ImageField(blank=True, default=None, null=True, upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Topbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('facebook_url', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('linkedin_url', models.CharField(max_length=255)),
                ('instagram_url', models.CharField(max_length=255)),
                ('youtube_url', models.CharField(max_length=255)),
            ],
        ),
    ]
