# Generated by Django 4.2.5 on 2023-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_icon', models.CharField(max_length=255)),
                ('about_adjective', models.CharField(max_length=30)),
                ('about_noun', models.CharField(max_length=30)),
            ],
        ),
    ]
