# Generated by Django 4.2.5 on 2023-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_aboutfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('service_detail', models.CharField(max_length=255)),
            ],
        ),
    ]
