# Generated by Django 4.2.5 on 2023-10-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_serviceheading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceheading',
            old_name='service',
            new_name='service_heading',
        ),
    ]
